/*
 * test_rng_parity.c -- assert lw_rng_double matches the Python port
 * (and therefore the Java engine) bit-for-bit on the first 8 outputs
 * for a panel of seeds.
 *
 * Golden values were generated by running:
 *
 *   python -c "..." (see scripts/gen_rng_golden.py once added)
 *
 * against leekwars._DefaultRandom (which itself was verified against
 * the Java engine).
 */

#include "lw_rng.h"
#include <stdio.h>
#include <string.h>
#include <inttypes.h>

typedef struct {
    int64_t  seed;
    uint64_t expected_bits[8];
} GoldenCase;

static const GoldenCase CASES[] = {
    /* These were dumped from leekwars._DefaultRandom on Python 3.14;
     * see commit message + ai_priv/bench_compare.py for context. */
    { 0LL,     { 0x3FE0000000000000ULL, 0x3FEA7B8000000000ULL, 0x3FC3828000000000ULL,
                 0x3FEACCA000000000ULL, 0x3FAB560000000000ULL, 0x3FD0880000000000ULL,
                 0x3FE7D5A000000000ULL, 0x3FD3478000000000ULL } },
    { 1LL,     { 0x3FE838C000000000ULL, 0x3FE2CFC000000000ULL, 0x3FC3C10000000000ULL,
                 0x3FD11B0000000000ULL, 0x3FEF296000000000ULL, 0x3FB5FC0000000000ULL,
                 0x3FD678C000000000ULL, 0x3FBCFC0000000000ULL } },
    { 42LL,    { 0x3FE9512000000000ULL, 0x3FD0A28000000000ULL, 0x3FE774A000000000ULL,
                 0x3FEC6EA000000000ULL, 0x3FCB108000000000ULL, 0x3FE088A000000000ULL,
                 0x3FE6ADA000000000ULL, 0x3FD9E14000000000ULL } },
    { 12345LL, { 0x3FEA7B8000000000ULL, 0x3FC3828000000000ULL, 0x3FEACCA000000000ULL,
                 0x3FAB560000000000ULL, 0x3FD0880000000000ULL, 0x3FE7D5A000000000ULL,
                 0x3FD3478000000000ULL, 0x3FC7AD8000000000ULL } },
    { 99999LL, { 0x3FEEB48000000000ULL, 0x3FEDC2A000000000ULL, 0x3FE0530000000000ULL,
                 0x3FB2020000000000ULL, 0x3FE35C6000000000ULL, 0x3FE0BFE000000000ULL,
                 0x3FEC28A000000000ULL, 0x3FDA760000000000ULL } },
    { -1LL,    { 0x3FCF1D0000000000ULL, 0x3FB13A0000000000ULL, 0x3FE4D0C000000000ULL,
                 0x3FED0BC000000000ULL, 0x3FE4412000000000ULL, 0x3FDB90C000000000ULL,
                 0x3FC1BC8000000000ULL, 0x3FDF500000000000ULL } },
};

static const int N_CASES = sizeof(CASES) / sizeof(CASES[0]);


static int test_one(const GoldenCase *c) {
    uint64_t state;
    lw_rng_seed(&state, c->seed);
    for (int i = 0; i < 8; i++) {
        double d = lw_rng_double(&state);
        uint64_t bits;
        memcpy(&bits, &d, 8);
        if (bits != c->expected_bits[i]) {
            fprintf(stderr,
                    "  seed %" PRId64 " call %d: got 0x%016" PRIX64
                    " expected 0x%016" PRIX64 "\n",
                    c->seed, i, bits, c->expected_bits[i]);
            return 0;
        }
    }
    return 1;
}


int main(void) {
    printf("test_rng_parity:\n");
    int ok = 1;
    for (int i = 0; i < N_CASES; i++) {
        int pass = test_one(&CASES[i]);
        printf("  seed %12" PRId64 ": %s\n",
               CASES[i].seed, pass ? "OK" : "FAIL");
        if (!pass) ok = 0;
    }
    return ok ? 0 : 1;
}
